### ISSUE TITLE
component won't mark as complete if you have more text than fits on screen

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-text#27]
if you have more text than can be displayed on screen at once (which usually occurs on a mobile device), this component won't mark as completed.

It's down to [this chunk of code](https://github.com/adaptlearning/adapt-contrib-text/blob/645a47c1e7470a77dfac220fd661107aa45976b5/js/adapt-contrib-text.js#L58-61) in the inview function - which basically says that both the top and bottom need to be displayed at the same time in order for the component to be completed.

**Comment by zenduo** [comment]
Hey @moloko / @darylhedley should this still be done?

https://github.com/adaptlearning/adapt-contrib-text/blob/develop/js/adapt-contrib-text.js#L58

Change this line to if (this._isVisibleBottom)?

Is this the same for https://github.com/adaptlearning/adapt-contrib-graphic/issues/34

**Comment by moloko** [comment]
hi @zenduo this and the contrib-graphic are both assigned to me in Jira; I need to do a bit more investigation before I decide what to do. Problem I've got is tracking down an actual instance of this bug to do some testing against, I know it has happened but I can't replicate it myself!

**Comment by oliverfoster** [comment]
original bug presented on old ios whereby javascript stops executing when scrolling. it was quite easy to pass a component whilst scrolling.

**Comment by zenduo** [comment]
This issue has been captured here: https://adaptlearning.atlassian.net/browse/ABU-344
