### ISSUE TITLE
Add Jest tests to our components

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt-contrib-text#64]
### Subject of the issue/enhancement/features
Enhancement:
Add Jest tests to our components

### Steps to run
Navigate to the `adapt-contrib-text` repo in the terminal and run `npm i; npm test;`

### Screenshots (if you can)
<img width="568" alt="Screenshot 2023-01-18 at 16 00 51" src="https://user-images.githubusercontent.com/61159216/213225116-9817cc6e-9e3f-409c-a84d-969cb171c994.png">

**Comment by oliverfoster** [comment]
closed for https://github.com/adaptlearning/adapt_framework/pull/3383
